### ISSUE TITLE
Update to pyt 1

### ISSUE THREAD

**Issue by jaideep11061982** [rasbt/deep-learning-book#72]
hi,thanks for very good work..
Have all the pytorch notebooks updated to pytorch 1 or some of them with last commit <5 days ago.

**Comment by rasbt** [comment]
Only 2 I think. This was because someone recommended writing something a bit differently to make it more readable, and hence it made sense to run the notebook in pytorch 1.0 instead of 0.4 since it had to be rerun anyway. For the other notebooks, I am 99% sure that there is no difference between 0.4 and 1.0. In the middle of a research project, I switched from 0.4 to 1.0 last month and I didn't notice any difference that would affect the notebooks. I am planning to run them in PyTorch 1.0 in any case soon though.
