### ISSUE TITLE
I want to read the book

### ISSUE THREAD

**Issue by maelfosso** [rasbt/deep-learning-book#77]
Hi,

Please I was on LeanPub but I don't see any link to read the different chapters.
I also check the tensorflow notebook but there is no order, there are not grouped by chapter.

Where could I read it please ?

**Comment by rasbt** [comment]
Sorry about that, I never got to finish the book, actually, which is why the chapters are not on leanpub, yet. I do have some rough drafts that I used to make the lecture slides for my DL class this semester: https://github.com/rasbt/stat479-deep-learning-ss19. When/before I am teaching the class again next year, I am planning to write out the actual lecture notes/chapters in a hopefully somewhat readable form.
